version: "3"
services:
  api:
    build:
      context: .
    image: api.reidchatham.com:dev
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      # POSTGRES_PORT: 27017
      EXPOSED_PORT: 443
    # env_file:
    #   - ./env/postgres.env
    ports:
      - 443:443
    # volumes:
    #   - ./:/app
    depends_on:
      - "db"
  db:
    image: postgres
    # env_file:
    #   - ./env/postgres.env
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
