version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api.reidchatham.com:dev
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      # POSTGRES_PORT: 27017
      EXPOSED_PORT: 8080
    ports:
      - 8080:8080
    # volumes:
    #   - ./:/app
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
