version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api.reidchatham.com:1.0.0
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      # POSTGRES_PORT: 27017
    ports:
      - 8080:8080
    # volumes:
    #   - ./:/app
    # networks:
    #   - webnet
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
# networks:
#   webnet:
